spring:
  application:
    name: shop-goods
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/trade
      username: root
      password: 123456

server:
  port: 8081

mq:
  order:
    consumer:
      group:
        name: shop

rocketmq:
  name-server: localhost:9876