#spring:
#  datasource:
#    druid:
#      url: jdbc:mysql://localhost:3306?xinghuan
#      username: root
#      password: 123456
# GROUP 不配置默认使用 DEFAULT_GROUP。
spring:
  application:
    name: nacos-config
  cloud:
    nacos:
      config:
        serverAddr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
  config:
    import:
      - nacos:locale
  messages:
    encoding: UTF-8
