spring:
  application:
    name: shop-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.37:8848
  datasource:
    druid:
      url: jdbc:mysql://192.168.2.37:3306/trade
      username: root
      password: 123456

server:
  port: 8084

rocketmq:
  name-server: 192.168.2.37:9876
  producer:
    group: orderProducerGroup

mq:
  order:
    consumer:
      group:
        name: order_orderTopic_cancel_group
    topic: orderTopic
    tag:
      cancel: order_cancel
