spring:
  application:
    name: shop-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/trade
      username: root
      password: 123456

server:
  port: 8084

rocketmq:
  name-server: 192.168.2.36:9876
  producer:
    group: orderProducerGroup

mq:
  order:
    topic: shop
    tag:
      cancel: cancel
