server:
  port: 8888

spring:
  redis:
    port: 6379
    host: localhost
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 123456
    driver: com.mysql.cj.jdbc.Driver
