spring:
  application:
    name: shop-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/trade
      username: root
      password: 123456

server:
  port: 8083

