spring:
  application:
    name: shop-pay
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/trade
      username: root
      password: 123456

server:
  port: 8084


rocketmq:
  producer:
    group: pay
  name-server:

mq:
  topic: payTopic
  pay:
    tag: paid

